### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by likai79511** [google/agera#165]
1.about Http part, lack to cookie manage.
2.seems agera directives both a specific purpose,such as getFrom.. getTranster...
in Rxjava, has  doOnNext..., just encapsulate Runnable.  if add this kind of  method in agera?

in additation to, If add some https config in http part, such as sslsocketFactory,Hostname verfy etc.

**Comment by maxtroy** [comment]
1) The HTTP extension is a sample extension that wraps a basic HTTP operation into a Function. You're free to fork the code and write your own Functions / Suppliers / Mergers.

2) What functionality do you wish the Runnable to be able to do in the Agera data flow? Note that inside the data flow, you can use getFrom / transform / mergeIn to modify the data, but you can also use sendTo / bindWith to send the intermediate result out of the flow for any "side" operation you want to perform. I'm not sure what the Runnables can do that's not already covered by the existing Agera functionality.

**Comment by likai79511** [comment]
Thans for you reply,let me know google haven't drop  agera(because agera framework have long time no update). that's great.

1. yes,I can extend API according requirement.
2.just a little thinking. because every directives both specific purpose. if I want to do other-action and no relate with data that pervious received,and then return previous received data. in this action will not use this data,just send to later directives.  but sure, transfer..etc also able to implementation  it. 

I will close this query. and hope Agera will go better,and hope you guys not drop it,because have many developer like it.

**Comment by maxtroy** [comment]
Thanks for your support!

About the second point, yes the directives have special names, but they're more about readability and convenience, and not about enforcement of the data flow. For example, all "mergeFrom" can be "transform" with a Function that reads an additional input from a Supplier; and all "sendTo" can be "transform" with an identity function with side effect. If you see the need to use the directives creatively, by all means go for it.

We are not dropping Agera; it's just so well designed and implemented, we haven't found a bug or a need for new features since the last update! :)
