### ISSUE TITLE
[Question] databaseQueryFunction returns List

### ISSUE THREAD

**Issue by krysanify** [google/agera#24]
While I understand that the extensions are just sample codes, is there any particular reason why databaseQueryFunction would return a List instead of the Cursor itself?

**Comment by ernstsson** [comment]
There's a few reasons:
Firstly, one of the key ideas behind Agera is to not do IO from the UI thread. Putting the cursor in a `Repository` wouldn't make sense for that reason, since a `Cursor` could potentially do heavy IO when interacted with. Secondly, `Cursor`s doesn't have to guarantee thread safety (and specifically `SQLiteCursor` does not) meaning passing them around to different threads is dangerous. Although this `Function` isn't strictly passing things to other threads or isn't really putting things directly in a `Repository` (this is up to the user of it to do) this helps developers not to make these mistakes.
Lastly and perhaps most importantly, `Cursor`s needs to be closed. Closing the `Cursor` in the same scope as opening it ensures we aren't leaking cursors.
That said; I have been using custom `Function`s returning a `Cursor` that's closed by the `Function` following it in the flow, but it does make the question of ownership (slightly) more difficult.

It is the very same reasons why the agera-net sample extension doesn't return `InputStream`s; it complicate ownership. The sample isn't suitable to do very large HTTP downloads (but I'd recommend against that anyway), but makes the most common cases of networking very simple. Sometimes a custom connection is needed instead, on a case by case basis.

**Comment by krysanify** [comment]
Ok, I understand now. A bit off topic, but does this mean CursorAdapter which directly link IO with UI considered dangerous as well? Thanks for the answer!

**Comment by ernstsson** [comment]
It is the same reason why `autoRequery` is discouraged in the `CursorAdapter` constructor, and why one of the constructors is deprecated with the following comment "_This option is discouraged, as it results in Cursor queries being performed on the application's UI thread and thus can cause poor responsiveness or even Application Not Responding errors._"
I personally feel it's fairly easy to make ownership mistakes if using `CursorAdapter`. `CursorAdapter` does `cursor.close()` in some cases, but ownership of the `Cursor` will be depending on how you decide to use it.

**Comment by krysanify** [comment]
cool.
