### ISSUE TITLE
BroadcastObservable

### ISSUE THREAD

**Issue by tonyshkurenko** [google/agera#26]
I tried to read sources and I found that if you subscribe on different actions you can't really get the type of the action? And also you can't get any data from the intent?

https://github.com/google/agera/blob/master/extensions/content/src/main/java/com/google/android/agera/content/ContentObservables.java#L104

**Comment by ernstsson** [comment]
The `broadcastObservable` in the content sample extension only helps with simple naive broadcasts. If you'd want data from a broadcast you can wrap this in a `Repository<SomeType>`. The wiki explains how to [implement custom observables](https://github.com/google/agera/wiki/Custom-observables). Since it sounds quite useful it's a good idea for an addition to the content sample extension though. I'll look into it

**Comment by ernstsson** [comment]
@tonyshkurenko hope you managed to wrap your data in a `Repository<SomeType>`? Closing this for now, but please feel free to ask more questions if this didn't work out.
